name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "?? The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "?? This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "?? The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "?? The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "??? The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "?? This job's status is ${{ job.status }}."
      - run: echo "Hello World! :D"
  Secret-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Secret Test
        run: echo "Oh whoa?"
#          if: 0 == 0
#          if [[ 1 == 1 ]]; then
        run: echo "What's this? :o"
#          fi
#          if [ "$SECRET_TEST" == 'test' ]
#          then
#            echo "YEET"
#          fi
#        env:
#          TESTING: ${{ secrets.SECRET_TEST }}
